Intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Intranet'

urlpatterns = [
    path('', views.index, name='index'),  # Main page of the Intranet app

    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),  # For login/logout

    path('kalendar/', include('kalendar.urls', namespace='kalendar')),  # <-- DŮLEŽITÉ
    path('pages/', include('pages.urls', namespace='pages')),  # Include pages app URLs
    path('diskuze/', include('diskuze.urls', namespace='diskuze')),  # Include discussion app URLs

    path('report/', include('report.urls', namespace='report')),  # Include report app URLs

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('comments/', include('django_comments.urls')),

    path('api/', include('api.urls')),  # Include API URLs
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from pages.views import PageViewSet
from diskuze.views import DiskuzeViewSet
from kalendar.views import EventViewSet

router = DefaultRouter()
router.register(r'pages', PageViewSet)
router.register(r'diskuze', DiskuzeViewSet)

# Přidej další routery zde...

urlpatterns = [
    path('', include(router.urls)),
    path('kalendar/', include('kalendar.urls')),
    path('diskuze/', include('diskuze.urls')),
    path('pages/', include('pages.urls')),
    path('api-auth/', include('rest_framework.urls')),  # Prohlížeč API


]

diskuze/urls.py
from django.urls import path, include
from . import views

app_name = 'diskuze'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:id>/', views.diskuze_detail, name='diskuze_detail'),
    path('add_message/<int:id>/', views.add_message, name='add_message'),
    path('add_discussion/', views.add_discussion, name='add_discussion'),
    path('delete_discussion/<int:id>/', views.delete_discussion, name='delete_discussion'),
]

pages/urls.py
from . import views
from django.urls import path, include

app_name = 'pages'

urlpatterns = [
    path('', views.page_list, name='page_list'),
    path('add/', views.add_page, name='add_page'),
    path('<slug:slug>/', views.page_detail, name='page_detail'),
    path('<slug:slug>/edit/', views.edit_page, name='edit_page'),
    # Add more URLs for the pages app as needed
]

diskuze/models.py
from django.db import models

# Create your models here.

class Zprava(models.Model):
    nazev = models.CharField(max_length=200, verbose_name="Název zprávy", null=True, default="Zpráva")
    obsah = models.TextField(verbose_name="Obsah zprávy")
    datum_vytvoreni = models.DateTimeField(auto_now_add=True, verbose_name="Datum vytvoření")
    autor = models.ForeignKey(
        'auth.User', on_delete=models.CASCADE, verbose_name="Autor zprávy"
    )

    def __str__(self):
        return self.nazev

    class Meta:
        verbose_name = "Zpráva"
        verbose_name_plural = "Zprávy"
        # Ordering by creation date (oldest first)
        ordering = ['-datum_vytvoreni']

class Diskuze(models.Model):
    nazev = models.CharField(max_length=200, verbose_name="Název diskuze")
    
    popis = models.TextField(verbose_name="Popis diskuze", blank=True, null=True)
    datum_zahajeni = models.DateTimeField(verbose_name="Datum zahájení diskuze", auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name="Datum aktualizace diskuze")

    zpravy = models.ManyToManyField(
        Zprava, 
        related_name='diskuze', 
        verbose_name="Zprávy v diskuzi"
    )

    def __str__(self):
        return self.nazev
    
    class Meta:
        verbose_name = "Diskuze"
        verbose_name_plural = "Diskuze"
        ordering = ['-datum_zahajeni']

templates/pages/add_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Nová stránka{% endblock %}

{% block content %}
<h2>Nová stránka</h2>
<form method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Přidat stránku</button>
</form>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            CKEDITOR.replace('id_content');
        });
    </script>
{% endblock %}

{% block extra_styles %}
{% endblock %}

templates/pages/edit_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2>Upravit stránku: {{ page.title }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Uložit změny</button>
</form>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            CKEDITOR.replace('id_content');
        });
    </script>
{% endblock %}

templates/pages/page_detail.html
{% extends "base.html" %}
{% block title %}Detail stránky: {{ page.title }}{% endblock %}

{% load static %}
{% load comments %}


{% block content %}
    <h1>{{ page.title }}</h1>
    <p>Datum vytvoření: {{ page.created|date:"d.m.Y H:i" }}</p>

    <hr>

    <div>{{ page.content|safe }}</div>

    <hr>

    <p>Poslední aktualizace: {{ page.updated|date:"d.m.Y H:i" }}, provedl 
        {% if page.updated_by %}
            {{ page.updated_by.first_name|default:"" }} {{ page.updated_by.last_name|default:"" }}
        {% else %}
            neznámý uživatel
        {% endif %}
    </p>

    <hr>

    <!--
    <h2>Diskuze k článku</h2>
    {% if diskuze_set %}
        <p>
            <a href="{% url 'diskuze:diskuze_detail' diskuze_set.id %}">
                <i class="fa-solid fa-comments"></i>
                Diskuze: {{ diskuze_set.nazev }}
            </a>

            <p>{{ diskuze_set.popis }}</p>

            <p>Počet zpráv: {{ diskuze_set.zpravy.count }}</p>
            
            <form method="post" action="{% url 'diskuze:add_message' diskuze_set.id %}">
                {% csrf_token %}
                {{ new_message_form.as_p }}
                <button type="submit" class="btn btn-primary">Přidat zprávu</button>
            </form>

            {% for zprava in diskuze_set.zpravy.all %}
                <div class="zprava">
                    <h3>{{ zprava.autor.first_name }} {{ zprava.autor.last_name }}</h3>
                    <p><strong>{{ zprava.nazev }}</strong><em>{{ zprava.datum_vytvoreni|date:"d.m.Y H:i" }}</em></p>
                    <p>{{ zprava.obsah|safe }}</p>
                </div>
            {% endfor %}
        </p>
    {% else %}
        <p>Diskuze k tomuto článku zatím neexistuje.</p>
    {% endif %}

    -->

    <!-- Comments section by Django Comments -->
    <h2>Komentáře</h2>
    
    {% render_comment_form for page %}

    <hr>

    {% render_comment_list for page %}

    <hr>

    <div class="link-container">
        <p>
            <a href="{% url 'pages:edit_page' slug=page.slug %}">
                <i class="fa-solid fa-pen-to-square"></i>
                Upravit stránku
            </a>
        </p>
        <p>
            <a href="{% url 'index' %}">
                <i class="fa-solid fa-backward"></i>
                Zpět na domovskou stránku
            </a>
        </p>
        <p>
            <a href="{% url 'pages:page_list' %}">
                <i class="fa-solid fa-list"></i>
                Zpět na seznam stránek
            </a>
        </p>
    </div>
{% endblock %}

{% block extra_scripts %}

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const inputName = document.querySelector('input[name="name"]');
            const inputEmail = document.querySelector('input[name="email"]');
            const inputUrl = document.querySelector('input[name="url"]');

            const labelName = document.querySelector('label[for="id_name"]');
            const labelEmail = document.querySelector('label[for="id_email"]');
            const labelUrl = document.querySelector('label[for="id_url"]');

            const inputPreview = document.querySelector('input[name="preview"]');

            inputName.value = "{{ user.get_full_name|default:'' }}";
            inputEmail.value = "{{ user.email|default:'' }}";
            inputUrl.value = "";
            inputPreview.value = "";

            inputName.style.display = 'none';
            inputEmail.style.display = 'none';
            inputUrl.style.display = 'none';
            inputPreview.style.display = 'none';

            labelName.style.display = 'none';
            labelEmail.style.display = 'none';
            labelUrl.style.display = 'none';            
        });
    </script>

{% endblock %}

templates/pages/page_list.html
{% extends "base.html" %}

{% block title %}Seznam stránek{% endblock %}

{% block content %}
<h2>Seznam stránek</h2>
<p>Vítejte v sekci stránek! Zde můžete spravovat své stránky
    a prohlížet si jejich obsah.</p>
<p>Pro přidání nové stránky, prosím, přejděte na <a href="{% url 'pages:add_page' %}">přidání stránky</a>.</p>
<ul class="big-list">
    {% for page in pages %}
        <a href="{% url 'pages:page_detail' slug=page.slug %}">
            <li>
                <strong>{{ page.title }}</strong>
                {% if page.updated %}
                    <span class="updated">Aktualizováno: {{ page.updated|date:"d.m.Y H:i" }}</span>
                {% endif %}
            </li>
        </a>
    {% empty %}
        <li>Žádné stránky k zobrazení.</li>
    {% endfor %}
</ul>
<p><a href="{% url 'index' %}">
    <i class="fa-solid fa-backward"></i>
    Zpět na domovskou stránku
</a></p>

{% endblock %}

{% block extra_scripts %}
<script>
    // JavaScript code can be added here if needed
</script>
{% endblock %}

{% block extra_styles %}
{% endblock %}